@tool
extends RefCounted

# TODO: Externalize to control util for use in other controls.
#       Stores cached theme items, generated by ThemeCacheBuilder.
class ThemeCache extends RefCounted:
    var _colors: Dictionary[StringName, Color] = {}
    var _constants: Dictionary[StringName, int] = {}
    var _fonts: Dictionary[StringName, Font] = {}
    var _font_sizes: Dictionary[StringName, int] = {}
    var _icons: Dictionary[StringName, Texture2D] = {}
    var _style_boxes: Dictionary[StringName, StyleBox] = {}

    func _init(builder: ThemeCacheBuilder) -> void:
        pass

    func update(control: Control) -> void:
        pass

# TODO: Holds required theme items and their fallback chain.
#       Method chaining for setting up.
#       Should be used as static variable for custom controls.
#       Can be used for handling theme overrides in _get, _set, _get_property_list
#       Generates theme cache object based on control reference.
#       Checks for theme overrides and then check if control has current variant theme item,
#       checks custom control type next, then base type,
#       then use fallbacks.
class ThemeCacheBuilder extends RefCounted:
    func _init(theme_type: StringName) -> void:
        pass

    # TODO: Create direct methods for all types
    func push_theme_item(data_type: Theme.DataType, name: StringName, is_overridable := true) -> ThemeCacheBuilder:
        return self

    func with_editor_fallback(name: StringName, theme_type: StringName) -> ThemeCacheBuilder:
        return self

    func with_fallback(name: StringName, theme_type: StringName) -> ThemeCacheBuilder:
        return self

    func with_fallback_value(value: Variant) -> ThemeCacheBuilder:
        return self

    func get_theme_override_property_list() -> Array[Dictionary]:
        return []

    func can_handle_property(property: String) -> bool:
        return true

    func handle_get_theme_override(control: Control) -> Variant:
        return null

    func handle_set_theme_override(control: Control) -> bool:
        return true
